### ISSUE TITLE
How to add the below local security policy setting which are not in the module

### ISSUE THREAD

**Issue by shreedharagowda** [ayohrling/local_security_policy#112]
@AndyAdrian-OP @ayohrling @silug 
Hi Andy/All 

How to add the below local security policy setting which are not in the module, Did try adding this settings in ayohrling-local_security_policy\lib\puppet_x\lsp\security_policy.rb file like below seems like some thing what I am trying is not right can you please kindly guide me how to get it working using this module & thanks in advance.

**Below are the extra setting that I tried adding in the security_policy.rb file**

      'Enforce user logon restrictions' => {
        name: 'EnforceUserLogonRestrictions',
        policy_type: 'System Access',
      },
      'Maximum lifetime for service ticket' => {
        name: 'MaximumLifetimeForServiceTicket',
        policy_type: 'System Access',
      },
      'Maximum lifetime for user ticket' => {
        name: 'MaximumLifetimeForUserTicket',
        policy_type: 'System Access',
      },
      'Maximum lifetime for user ticket renewal' => {
        name: 'MaximumLifetimeForUserTicketRenewal',
        policy_type: 'System Access',
      },
      'Maximum Tolerance For Computer Clock Synchronization' => {
        name: 'MaximumToleranceForComputerClockSynchronization',
        policy_type: 'System Access',
      },

**Below is the class file settings**

local_security_policy { 'Enforce user logon restrictions':
  ensure       => present,
  policy_value => '1',
}

local_security_policy { 'Maximum lifetime for service ticket':
  ensure       => present,
  policy_value => '600',
}

local_security_policy { 'Maximum lifetime for user ticket':
  ensure       => present,
  policy_value => '10',
}

local_security_policy { 'Maximum lifetime for user ticket renewal':
  ensure       => present,
  policy_value => '7',
}

local_security_policy { 'Maximum tolerance for computer clock synchronization':
  ensure       => present,
  policy_value => '5',
}

**Below is the GPresult Screenshots**
![image](https://user-images.githubusercontent.com/96411173/152547810-333562a5-7db9-40b1-98ec-2f83fceef531.png)
![image](https://user-images.githubusercontent.com/96411173/152547907-66c6715e-931c-4329-9963-4eb4bee61d04.png)

**Comment by AndyAdrian-OP** [comment]
This module manages only Local Security Policy settings, by using `secedit.exe`.   Sadly, the specific policies you're looking at can't be modified with `secedit` locally.

**Comment by ayohrling** [comment]
These are specifically kerberos relevant settings when connected to a domain for login anyway; thus are only likely manageable through GPO.

**Comment by shreedharagowda** [comment]
Hi Thanks a lot for both of you for your kind inputs and time really apricate it.
