### ISSUE TITLE
log on as a service timeout?

### ISSUE THREAD

**Issue by logicminds** [ayohrling/local_security_policy#13]
This seems to time out on my system.   

You can use `puppet resource local_security_policy 'Log on as a service'` to get the current values

Was just curious if anyone else was using something similar to:

```
local_security_policy{'Log on as a service':
   ensure => present,
   policy_setting => 'SeServiceLogonRight',
   policy_type     => 'Privilege Rights',
   policy_value   => 'values_go_here'
}
```

**Comment by logicminds** [comment]
From what I can this might be caused when using GPOs to enforce the setting and the local system user that puppet runs as cannot change the values.

**Comment by ayohrling** [comment]
I haven't got this running anywhere handy as I don't have any managed Windows boxes in my current environment (this was initially for a client), but I recall having no issues with this when running in CMD as a local administrator regardless of whether the policies were enforced by GPO or by local group policy.

**Comment by AndyAdrian-OP** [comment]
Stale ticket, unable to reproduce.
