### ISSUE TITLE
Wrong value returned

### ISSUE THREAD

**Issue by jkotecki** [ayohrling/local_security_policy#16]
When I issue fetch the resource 'Interactive logon: Machine inactivity limit' it returns with the incorrect value. I have it set to 900, but what gets returned is 4,900. I assume that the 4 is actually the reg_type.

C:\Windows\system32>puppet resource local_security_policy 'Interactive logon: Machine inactivity limit'
local_security_policy { 'Interactive logon: Machine inactivity limit':
  ensure         => 'present',
  policy_setting => 'MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\
System\InactivityTimeoutSecs',
  policy_type    => 'Registry Values',
  policy_value   => '4,900',
}

**Comment by AndyAdrian-OP** [comment]
This is as designed.  The module works by exporting the Local Security Policy settings to an INF file using secedit.exe, then reading the contents of that file.  For registry settings defined in the file, the value includes the registry data type.
