### ISSUE TITLE
module dumps all users/groups in AD to csv

### ISSUE THREAD

**Issue by GerbenWelter** [ayohrling/local_security_policy#20]
Hi,

When running the module as a non-local user (e.g. an AD-user with local admin rights) the method 'local_users' using WMIC.exe dumps the complete list of users and group present in the Active Directory. Depending on the size and speed, this can take anywhere from 5 to 15 minutes in my experience. This takes place on every Puppet run and makes coding/testing very difficult.

@ayohrling Is there a reason the way it is implemented now? Do we need the complete list of objects/SIDs? Is it possible to cache this information and only expire it after a certain time? Or can we query the AD for the information when needed for a particular user/group?

There are gems for querying the AD from Ruby natively (using LDAP) but before I explore that route I would like to know the rationale for the current implementation.

Gerben

**Comment by ayohrling** [comment]
Honestly that code using WMIC was in there in the original implementation. I have forked it, fixed issues, and invited the collaboration to try and keep it updated (original implementation did not respond to PRs at all). I believe that there was plans to support the SID/User mapping and conversion for all users including those in AD when the system is a member of a domain. I would probably agree this is not the most efficient way, but even using direct Ruby connectivity to LDAP may still possibly be slow. We'd have to find a way to query only the local users, then query the AD users separate and combine them; still probably somewhat inefficient. Perhaps could tune the module to accept a setting whether to use AD at that point or not though.

**Comment by trlinkin** [comment]
Hey, PR #28 is my attempt to fix this. Please take a look :)

**Comment by AndyAdrian-OP** [comment]
Issue resolved in https://github.com/ayohrling/local_security_policy/pull/28.  Closing ticket.
