### ISSUE TITLE
Could not evaluate: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by logicminds** [ayohrling/local_security_policy#3]
Could not evaluate: undefined method `[]' for nil:NilClass

This seems to be happening while using the following code

```puppet
local_security_policy { 'Network access: Let Everyone permissions apply to anonymous users':
    ensure         => 'present',
    policy_setting => 'MACHINE\System\CurrentControlSet\Control\Lsa\EveryoneIncludesAnonymous',
    policy_type    => 'Registry Values',
    policy_value   => '0',
  }
```

**Comment by ayohrling** [comment]
Tracked this down, from the original author, there is a capitalization issue. Will fix and merge.

**Comment by ayohrling** [comment]
Merge PR#4, updated version to 0.4.1; pushed tag and releasing to Puppet Forge.
