### ISSUE TITLE
Accounts: Administrator Account Status LSP is not supported by Module

### ISSUE THREAD

**Issue by naeem98** [ayohrling/local_security_policy#33]
We are doing windows hardening by modifying LSP settings and modifying registry keys according to CIS standards but the current version of module does not support the LSP setting 'Accounts: Administrator Account Status' 

Is it possible to have this feature available in this module?

**Comment by ayohrling** [comment]
Resolved in 0.6.3 released to Forge.

**Comment by TheITRx** [comment]
Howdy team, 

how about for "Accounts: Guest account status". It does not appear to be a supported. LSP in this module.
